name: Build and Push Frontend Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Obtener el código
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Buildx (permite multi-plataforma y caché eficiente)
      - uses: docker/setup-buildx-action@v2

      # 3️⃣ Login seguro a Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Construir y subir imagen con múltiples tags
      - uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            angeel22m/proyecto-frontend:latest
            angeel22m/proyecto-frontend:${{ github.ref_name }}
            angeel22m/proyecto-frontend:${{ github.sha }}
          cache-from: type=registry,ref=angeel22m/proyecto-frontend:latest
          cache-to: type=inline